### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by jodastephen** [er1c/scala-joda-money#2]
While I understand that the code is a port, the `org.joda` packages are effectively "owned" by me. As such, you should use a different package really. Not sure why Scala can't just use the Java library anyway.

**Comment by er1c** [comment]
@jodastephen Ahh the reason for the port is to transpile it to `scala-js` (https://www.scala-js.org/) - so it can be a "drop-in replacement" for other scala code that uses the java library, to javascript-based code.  Especially useful for shopping-carts where having to SUM up different strongly-typed currencies/etc.  As a reference, I have a shared scala interface like `CartItem` that has a `price` of type `BigMoney`.  The backend API uses the interface to serialize the data to JSON (response from an ajax request), where the javascript frontend (written in scala) also uses/shares the same interface `CartItem`.

**Comment by jodastephen** [comment]
I think you can do this and not change the [ackage name, just be clear on the website for the rationale.
